# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 860c6311e9591c860047ea1f91909e740beedfe7ae87640910a18ca36d2a410876a22da457d7e44fe526c5dbe0f68249f14325ba8ebdf4f80eb45ccc5307e68c

test:
  secret_key_base: a35847a3679f45d23050c364760ff0a898d4c4ad440116d7f4490a3c8f632d189d5a5b79bd8860f8219156f9ba3c1db6b76a33d1905c78f2c5ae329d40647723

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
